export interface MapTheme {
  name: string;
  description: string;
  bg: string;
  text: string;
  gradient_color: string;
  water: string;
  parks: string;
  road_motorway: string;
  road_primary: string;
  road_secondary: string;
  road_tertiary: string;
  road_residential: string;
  road_default: string;
}

export const mapThemes: MapTheme[] = [
  {
    name: "Strava Dark",
    description: "Premium charcoal map with vivid Strava orange route accent",
    bg: "#0A0A0A",
    text: "#F4EFE6",
    gradient_color: "#0A0A0A",
    water: "#10161C",
    parks: "#0E1410",
    road_motorway: "#2A2A2A",
    road_primary: "#FC4C02",
    road_secondary: "#1F1F1F",
    road_tertiary: "#181818",
    road_residential: "#141414",
    road_default: "#FC4C02",
  },
  {
    name: "Forest",
    description: "Deep greens and sage tones - organic botanical aesthetic",
    bg: "#F0F4F0",
    text: "#2D4A3E",
    gradient_color: "#F0F4F0",
    water: "#B8D4D4",
    parks: "#D4E8D4",
    road_motorway: "#2D4A3E",
    road_primary: "#3D6B55",
    road_secondary: "#5A8A70",
    road_tertiary: "#7AAA90",
    road_residential: "#A0C8B0",
    road_default: "#7AAA90",
  },
  {
    name: "Ocean",
    description: "Various blues and teals - perfect for coastal cities",
    bg: "#F0F8FA",
    text: "#1A5F7A",
    gradient_color: "#F0F8FA",
    water: "#B8D8E8",
    parks: "#D8EAE8",
    road_motorway: "#1A5F7A",
    road_primary: "#2A7A9A",
    road_secondary: "#4A9AB8",
    road_tertiary: "#70B8D0",
    road_residential: "#A0D0E0",
    road_default: "#4A9AB8",
  },
  {
    name: "Monochrome Blue",
    description: "Single blue color family with varying saturation - clean and cohesive",
    bg: "#F5F8FA",
    text: "#1A3A5C",
    gradient_color: "#F5F8FA",
    water: "#D0E0F0",
    parks: "#E0EAF2",
    road_motorway: "#1A3A5C",
    road_primary: "#2A5580",
    road_secondary: "#4A7AA8",
    road_tertiary: "#7AA0C8",
    road_residential: "#A8C4E0",
    road_default: "#4A7AA8",
  },
  {
    name: "Gradient Roads",
    description: "Smooth gradient from dark center to light edges with subtle features",
    bg: "#FFFFFF",
    text: "#000000",
    gradient_color: "#FFFFFF",
    water: "#D5D5D5",
    parks: "#EFEFEF",
    road_motorway: "#050505",
    road_primary: "#151515",
    road_secondary: "#2A2A2A",
    road_tertiary: "#404040",
    road_residential: "#555555",
    road_default: "#404040",
  },
  {
    name: "Emerald City",
    description: "Lush dark green aesthetic with mint accents",
    bg: "#062C22",
    text: "#E3F9F1",
    gradient_color: "#062C22",
    water: "#0D4536",
    parks: "#0F523E",
    road_motorway: "#4ADEB0",
    road_primary: "#2DB88F",
    road_secondary: "#249673",
    road_tertiary: "#1B7559",
    road_residential: "#155C46",
    road_default: "#155C46",
  },
  {
    name: "Autumn",
    description: "Burnt oranges, deep reds, golden yellows - seasonal warmth",
    bg: "#FBF7F0",
    text: "#8B4513",
    gradient_color: "#FBF7F0",
    water: "#D8CFC0",
    parks: "#E8E0D0",
    road_motorway: "#8B2500",
    road_primary: "#B8450A",
    road_secondary: "#CC7A30",
    road_tertiary: "#D9A050",
    road_residential: "#E8C888",
    road_default: "#CC7A30",
  },
  {
    name: "Terracotta",
    description: "Mediterranean warmth - burnt orange and clay tones on cream",
    bg: "#F5EDE4",
    text: "#8B4513",
    gradient_color: "#F5EDE4",
    water: "#A8C4C4",
    parks: "#E8E0D0",
    road_motorway: "#A0522D",
    road_primary: "#B8653A",
    road_secondary: "#C9846A",
    road_tertiary: "#D9A08A",
    road_residential: "#E5C4B0",
    road_default: "#D9A08A",
  },
  {
    name: "Warm Beige",
    description: "Earthy warm neutrals with sepia tones - vintage map aesthetic",
    bg: "#F5F0E8",
    text: "#6B5B4F",
    gradient_color: "#F5F0E8",
    water: "#DDD5C8",
    parks: "#E8E4D8",
    road_motorway: "#8B7355",
    road_primary: "#A08B70",
    road_secondary: "#B5A48E",
    road_tertiary: "#C9BBAA",
    road_residential: "#D9CFC2",
    road_default: "#C9BBAA",
  },
  {
    name: "Sunset",
    description: "Warm oranges and pinks on soft peach - dreamy golden hour aesthetic",
    bg: "#FDF5F0",
    text: "#C45C3E",
    gradient_color: "#FDF5F0",
    water: "#F0D8D0",
    parks: "#F8E8E0",
    road_motorway: "#C45C3E",
    road_primary: "#D87A5A",
    road_secondary: "#E8A088",
    road_tertiary: "#F0B8A8",
    road_residential: "#F5D0C8",
    road_default: "#E8A088",
  },
  {
    name: "Contrast Zones",
    description: "Strong contrast showing urban density - darker in center, lighter at edges",
    bg: "#FFFFFF",
    text: "#000000",
    gradient_color: "#FFFFFF",
    water: "#B0B0B0",
    parks: "#ECECEC",
    road_motorway: "#000000",
    road_primary: "#0F0F0F",
    road_secondary: "#252525",
    road_tertiary: "#404040",
    road_residential: "#5A5A5A",
    road_default: "#404040",
  },
];
